[2021-05-12 11:14:56,778] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task1 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 11:14:56,785] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task1 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 11:14:56,785] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 11:14:56,786] {taskinstance.py:1069} INFO - Starting attempt 7 of 8
[2021-05-12 11:14:56,786] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 11:14:56,923] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task1> on 2021-05-12T10:39:48.267484+00:00
[2021-05-12 11:14:56,925] {standard_task_runner.py:52} INFO - Started process 2203048 to run task
[2021-05-12 11:14:56,931] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task1', '2021-05-12T10:39:48.267484+00:00', '--job-id', '100', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmp2ufofdgk', '--error-file', '/tmp/tmp4jdi3fh7']
[2021-05-12 11:14:56,931] {standard_task_runner.py:77} INFO - Job 100: Subtask task1
[2021-05-12 11:14:57,056] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task1 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-12 11:14:57,193] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-12 11:14:57,193] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-12 11:14:57,194] {bash.py:158} INFO - Running command: echo im task 1 !!!!!!!!!!!!!!!!!!!! || exit 1
[2021-05-12 11:14:57,203] {bash.py:169} INFO - Output:
[2021-05-12 11:14:57,204] {bash.py:173} INFO - im task 1 !!!!!!!!!!!!!!!!!!!!
[2021-05-12 11:14:57,205] {bash.py:177} INFO - Command exited with return code 0
[2021-05-12 11:14:57,334] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task1, execution_date=20210512T103948, start_date=20210512T111456, end_date=20210512T111457
[2021-05-12 11:14:57,614] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-12 11:14:57,628] {local_task_job.py:146} INFO - Task exited with return code 0
