[2021-05-13 04:47:29,551] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:47:29,559] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:47:29,559] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:47:29,559] {taskinstance.py:1069} INFO - Starting attempt 12 of 13
[2021-05-13 04:47:29,559] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:47:29,665] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task4> on 2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:47:29,668] {standard_task_runner.py:52} INFO - Started process 2893390 to run task
[2021-05-13 04:47:29,673] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task4', '2021-05-12T10:39:48.267484+00:00', '--job-id', '139', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmpsanbspvu', '--error-file', '/tmp/tmp475t9obm']
[2021-05-13 04:47:29,674] {standard_task_runner.py:77} INFO - Job 139: Subtask task4
[2021-05-13 04:47:29,882] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-13 04:47:30,019] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task4
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:47:30,020] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-13 04:47:30,020] {bash.py:158} INFO - Running command: airflow tasks clear -f status_test -y
[2021-05-13 04:47:30,031] {bash.py:169} INFO - Output:
[2021-05-13 04:47:31,029] {bash.py:173} INFO - [2021-05-13 04:47:31,028] {dagbag.py:451} INFO - Filling up the DagBag from /root/airflow/dags
[2021-05-13 04:47:31,044] {bash.py:173} INFO - /home/ubuntu/venv/lib/python3.8/site-packages/airflow/utils/decorators.py:94 DeprecationWarning: provide_context is deprecated as of 2.0 and is no longer required
[2021-05-13 04:47:31,380] {bash.py:177} INFO - Command exited with return code 0
[2021-05-13 04:47:31,485] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task4, execution_date=20210512T103948, start_date=20210513T044729, end_date=20210513T044731
[2021-05-13 04:47:31,613] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-13 04:47:31,621] {local_task_job.py:146} INFO - Task exited with return code 0
